### ISSUE TITLE
Move ff-tool/.cache dir to user's home dir:  ~/.ff-tool

### ISSUE THREAD

**Issue by rpappalax** [rpappalax/ff-tool#103]
The default behavior for many tools requiring caching is to simply have 1 cache in the user's home dir.  I can think of many pros to doing this but namely if you have multiple clones of ff-tool, all your browser downloads are in one place so you never be downloading the same browser you have elsewhere in your dir structure.  Also, you'd never clobber profiles because we've designed it so that can't happen anyway.

@pdehaan thoughts?

**Comment by rpappalax** [comment]
Per our discussion, this tool is very installation-centric and would probably be more likely to be installed in more than one place.  Hence, retaining cache local to tool installation dir is preferable.  Also, this way the tool is entirely self-contained.

**Comment by pdehaan** [comment]
If you _want_ a globally installed profile, you can create a shared directory in the location of your choosing, and do something like this:

```sh
$ ff -c nightly -p ~/.shared-dir/my-profile-name --addon https://moz-activity-streams-dev.s3.amazonaws.com/dist/activity-streams-latest.xpi
```
