### ISSUE TITLE
[docs] do we want to use readthedocs?

### ISSUE THREAD

**Issue by rpappalax** [rpappalax/ff-tool#15]
i like the simplicity of .md files except when they become too scrolly.
it might be nice to have the docs on the readthedocs so we can have a section to click to that talks about the special use-case for cloud services testing.
just a thought.

**Comment by pdehaan** [comment]
I think is possibly overkill for this repo for now, but let's keep this open for :poop: and :grinning:.

**Comment by rpappalax** [comment]
the rst file seems adequate for a package hosted on Pypi so going to close for now
