### ISSUE TITLE
Add linux platform

### ISSUE THREAD

**Issue by rpappalax** [rpappalax/ff-tool#23]
ok, i've added a linux.ini file (but only because my version of ubuntu detects os as "linux" and not "linux-gnu".  using the same file verbatim that was in services-test/_utils

Here's how far i get:

env)rpappalax@vimdiesel:~/git/ff-tool$ ff -c nightly

----------------------------------------
LOADING configs/linux.ini
----------------------------------------

----------------------------------------
LOADING configs/linux.ini
----------------------------------------

----------------------------------------
LOADING configs/linux.ini
----------------------------------------

Downloading nightly to _temp/browsers/firefox-nightly.tar.bz2
/home/rpappalax/git/ff-tool/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/rpappalax/git/ff-tool/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/home/rpappalax/git/ff-tool/venv/bin/ff", line 9, in <module>
    load_entry_point('ff-tool==0.0.1', 'console_scripts', 'ff')()
  File "/home/rpappalax/git/ff-tool/fftool/main.py", line 14, in main
    download(options.channel)
  File "/home/rpappalax/git/ff-tool/fftool/firefox_download.py", line 69, in download
    install(channel)
  File "/home/rpappalax/git/ff-tool/fftool/firefox_install.py", line 23, in install
    local('tar -jxf {0} && mv firefox {1}'.format(installer, install_dir))  # NOQA
NameError: global name 'installer' is not defined

**Comment by pdehaan** [comment]
FIxed in #21
