### ISSUE TITLE
Remove references to _temp/{browsers,profiles}/

### ISSUE THREAD

**Issue by pdehaan** [rpappalax/ff-tool#25]
Currently we do a neat trick of adding globals in `__init__.py`, so we should remove any references from _temp/browsers/ and _temp/profiles/ in any *.py or *.ini files and just isolate all references to one place.

**Comment by rpappalax** [comment]
I grepped thru all the files and this has been resolved so, closing.
NOTE:
There is a cache file reference in firefox_uninstall.py that looks for a "cache.ini" file, but that seems to have been established before we even put a _temp dir in place - it pre-dates any constants being declared in __init__.py (and I don't believe the uninstall code has been used in awhile), so I'll create a separate issue to verify it still works properly.
