### ISSUE TITLE
Replace Fabric w/ Popen

### ISSUE THREAD

**Issue by pdehaan** [rpappalax/ff-tool#39]
Currently we're using both (for technical reasons I now forget).

It'd be nice to standardize on one, if possible. And since we started with Fabric and switched to Popen, I'm guessing we should just try and stick w/ Popen since obviously there was something that we were having issues doing w/ Fabric.

**Comment by rpappalax** [comment]
I totally agree.  Fabric is clean from the user side but makes for a way too long install since it compiles a bunch of c code stuff.  let's move to Popen.
