### ISSUE TITLE
feat: figure out how to have multiple pref sets for one test-env

### ISSUE THREAD

**Issue by rpappalax** [rpappalax/ff-tool#45]
There are a few projects (like shavar) that have multiple pref sets for 1 test environment (i.e. STAGE).  Currently our tool is designed around a section header being a test env (like [stage]).  

We'll need to figure out a way to adapt this so you could have multiple "named" pref sets for one test env.

https://wiki.mozilla.org/Services/TrackingProtection/Shavar_Server_-_Testing#SET_CUSTOM_PREFS

**Comment by rpappalax** [comment]
:hurtrealbad: :rage1: :pouting_cat: :dizzy_face: :poop:

**Comment by rpappalax** [comment]
without creating some crazy hierarchy or trying to move away from ini to something more layered, there may be another solution where we use our standard test-env names (dev, stage, prod) as "prefixes" for each named environment:  i.e. (for shavar)

[stage-moztestpub]
[stage-mozstd]
[stage-mozfull]
[stage-mozstaging]

The above would accomodate 4 pref sets for STAGE.
We might have to add logic to "parse out" section headers with the desired prefix.

**Comment by rpappalax** [comment]
Do we have a 'prefs' branch for services-test we're working with?  If not, let's create one and I can load in some real pref sets for autopush, loop-server, loop-client, shavar.  Perhaps if you have some for different projects, we can add them in too.

**Comment by rpappalax** [comment]
I think the challenge with these will be when pref sets become mutually exclusive (or don't).  For example, we may have one project that has multiple pref sets, but when unspecified, the [DEFAULT] option would be acceptable.  Unfortunately, for shavar, that will never be the case (aka: there is never a DEFAULT).  In such a case as that, we'd need to short-circuit the user's choice and say:  "Sorry, there is no default option, you can choose from the following: 
[stage-moztestpub]
[stage-mozstd]
[stage-mozfull]
[stage-mozstaging]
I'm not sure the best way to handle all such cases, but maybe we can tackle each project one at a time and see if there's some over-arching logic for handling defaults that makes sense universally

**Comment by pdehaan** [comment]
Dev, stage, and prod are irrelevant names, they could be anything. Since this is our most advanced use case (so far), it'd be interesting to whiteboard this. But yeah, early tests could be maybe envs like `[stage:mozfull]` and see if it can handle a`--env stage:mozfull` on the cli (where all shared configs could be in a [DEFAULT], or something.
I'd like to stay away from adding too many more flags, but we could add ability to specify a custom `--prefs-file` and append that to our other configs.

:poop: indeed!

**Comment by rpappalax** [comment]
On a similar note, we've setup our services-test repo to assume there will only be 1 test per test-type, but it seems unlikely that will always apply.  If we can think thru this issue, I think it will become clearer how to handle issues like that in other places.

**Comment by rpappalax** [comment]
Looks like this may be somewhat more complex.  we need to be able to have the following:

- global prefs - apply to all test environments all the time

- global pref "sets" - apply to all test environments, but these would vary.  for example: global pref set A (mozstd), global pref set B (moztestpub), etc.

- specific prefs (for 1 test-env - i.e. stage only)

I think this could be achieved at least on the arg side like so:

ff -a shavar -e stage+mozstd

**Comment by rpappalax** [comment]
Blocks mozilla-services/services-test#91

**Comment by rpappalax** [comment]
We can now specify multiple pref sets with this branch.  A first use case is shavar - see:
https://github.com/mozilla-services/services-test/blob/dev/shavar/e2e-test/prefs.ini#L19-L40

to specify "stage" and "mozpub" simple specify  ff -a shavar -e test-type -f  stage+mozpub
