### ISSUE TITLE
[os: win] add a logical OR to all ostype conditionals for "cygwin" || "windows"

### ISSUE THREAD

**Issue by rpappalax** [rpappalax/ff-tool#46]
Cygwin on windows server determines the OS as "cygwin" and, hence, tragically fails when it can't find a configs/cygwin.ini.  However, we also know that Win10 cygwin determins the OS as "windows".
:scream_cat:

**Comment by pdehaan** [comment]
What are we doing? We have [this code](https://github.com/rpappalax/ff-tool/blob/371a46da913afb75c78cfc94523ee737967ee370/fftool/firefox_env_handler.py#L18-L29) which does some defensive anti-Cygwin logic when trying to load OS-specific configs.
Wondering if there is some other sharp edge you're finding where we need similar logic, or if we need to beef up "is_windows()" logic somewhere.

```py
    def get_os():
        system = platform.system().lower()
        system = re.split('[-_]', system, maxsplit=1).pop(0)

        if system == "cygwin":
            return "windows"

        return system
```

**NOTE:** That regex nonsense was to try and short circuit some similar results where linux was self identifying as "linux" or "linux_gnu".

**Comment by rpappalax** [comment]
thanks, Peter. i'll try and reverify on the slave.

**Comment by rpappalax** [comment]
my bad :8ball:
