### ISSUE TITLE
Add `ff --clean-profiles` flag

### ISSUE THREAD

**Issue by pdehaan** [rpappalax/ff-tool#48]
Add a `$ ff --clean-profiles` flag which deletes the _temp/profiles directory to avoid lingering profiles.

During investigation it appears that EACH profile takes up ~15MB of space, which is bad.

**Comment by rpappalax** [comment]
In the pipeline (groovy job generation), we will need to add a post-build-step to run:
ff --clean-profiles

**Comment by pdehaan** [comment]
Possible approach:

- Use Popen() to rimraf the _temp/profiles/fftool.* directories.
- Put that ^^ code in the [./fftool/firefox_profile.py](https://github.com/rpappalax/ff-tool/blob/dev/fftool/firefox_profile.py) file.
- Create a `--clean-profiles` flag in [./fftool/ff_cli.py](https://github.com/rpappalax/ff-tool/blob/dev/fftool/ff_cli.py) which we call from [./fftool/main.py](https://github.com/rpappalax/ff-tool/blob/dev/fftool/main.py).

**Comment by rpappalax** [comment]
:+1:
