### ISSUE TITLE
Add ability to launch browser w/ specific addon

### ISSUE THREAD

**Issue by rpappalax** [rpappalax/ff-tool#56]
this would be very handy for gofaster testing.
:runner:  :hourglass_flowing_sand:

**Comment by pdehaan** [comment]
Some progress...

1. Create a new profile via `mozprofile`:

    ```sh
$ mozprofile -p peter.panda2 -a http://people.mozilla.org/\~bwinton/TabCenter/tab_center_test-1.9-fx.xpi
```

2. Launch Firefox using our custom, local profile:

    ```sh
$ /Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox --profile ./peter.panda2
```

Unfortunately, that begets the following error/warning in Das Terminal:
```
addons.xpi-utils	WARN	Disabling foreign installed add-on tabcentertest1@mozilla.com in app-profile
```

The browser launches as expected, and the add-on is installed in "about:addons", BUT the add-on isn't enabled. Not specific to that XPI, I tried with 2 others (not a great sample size, but "meh"). It's easy enough for me to manually enable that add-on, but for automated tests, that's somewhat amateur hour.

We must go further down the 🐇 hole.

**Comment by rpappalax** [comment]
per davehunt: you'd need to specify the add-on in your mozprofile

**Comment by rpappalax** [comment]
@pdehaan this looks promising:
http://mozbase.readthedocs.io/en/latest/mozprofile.html#module-mozprofile.addons

 install_from_path(path, unpack=False)[source]
    Installs addon from a filepath, url or directory of addons in the profile.

**Comment by rpappalax** [comment]
i feel silly, i believe you already tried this @pdehaan
