### ISSUE TITLE
[bug] clean profiles doesn't remove profiles

### ISSUE THREAD

**Issue by rpappalax** [rpappalax/ff-tool#58]
this is true (at least for configs/darwin.ini)

**Comment by rpappalax** [comment]
This line should only be activated conditionally for Windows OS:
https://github.com/rpappalax/ff-tool/blob/dev/fftool/firefox_profile.py#L60

**Comment by pdehaan** [comment]
![](http://data.whicdn.com/images/44285779/large.gif)

I'll look into dis.
