### ISSUE TITLE
Add --version flag

### ISSUE THREAD

**Issue by pdehaan** [rpappalax/ff-tool#61]
```bash
$ ff --version

----------------------------------------
LOADING configs/darwin.ini
----------------------------------------

usage: ff [-h] [-c {release,beta,aurora,nightly,ALL}] [-p PROFILE] [-e ENV]
          [-t TEST_TYPE] [-a APP] [--no-launch] [--no-profile]
          [--install-only] [--clean-profiles]
ff: error: unrecognized arguments: --version
```

Probably just return the `__version__` string from [./fftool/__init__.py:7](https://github.com/rpappalax/ff-tool/blob/1ed3a6a49912b2b4dd61c64a2fa20167f4ae7a79/fftool/__init__.py#L7) or somethin'.

**Comment by rpappalax** [comment]
@pdehaan:  I assume you mean print out version of ff-tool, yes?

btw, all other options already print the firefox version (including --install-only)

----------------------------------------
DOWNLOAD FIREFOX
----------------------------------------

Downloading nightly to _temp/browsers/FirefoxNightly.dmg

----------------------------------------
BROWSER VERSION
----------------------------------------

You have the latest version of nightly installed (Mozilla Firefox 49.0a1).
