### ISSUE TITLE
feat: add support for python3

### ISSUE THREAD

**Issue by rpappalax** [rpappalax/ff-tool#62]
seems like mozprofile may also be limited to python3 atm:
(venv) : $ python --version
Python 3.4.4
(venv) : $ pip install -r requirements.txt
Collecting mozdownload==1.20.2 (from -r requirements.txt (line 1))
  Downloading mozdownload-1.20.2.tar.gz
Collecting mozprofile==0.28 (from -r requirements.txt (line 2))
  Using cached mozprofile-0.28.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1n/znmq6xc95wq38tm9qh93bz7r0000gn/T/pip-build-1r7ljues/mozprofile/setup.py", line 12, in <module>
        assert sys.version_info[0] == 2
    AssertionError
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/1n/znmq6xc95wq38tm9qh93bz7r0000gn/T/pip-build-1r7ljues/mozprofile/

**Comment by rpappalax** [comment]
will need to update fftool/firefox_download.py

and tox and travis files

**Comment by pdehaan** [comment]
Not sure if mozprofile supports Python3. Will need to dig deeper.

**Comment by rpappalax** [comment]
thanks @pdehaan!
https://bugzilla.mozilla.org/show_bug.cgi?id=1093212

**Comment by pdehaan** [comment]
Closing this for now, since we're blocked upstream by mozbase not supporting Python 3 yet for unknown reasons.
