### ISSUE TITLE
[feat] push to PyPI

### ISSUE THREAD

**Issue by rpappalax** [rpappalax/ff-tool#66]
should be ready to go, but we'll need to verify that pip install is working properly.
Also, since mozbase locks us into python2.x, I'd like to add a  graceful failure msg which references the bug for mozbase supporting python 3

**Comment by pdehaan** [comment]
I think this was completed: https://pypi.python.org/pypi/ff-tool/

**Comment by rpappalax** [comment]
it was, but will need to tweak things a bit ensure to that pip install is working properly for any user that tries it.  once we figure out what we need for outlawg or whatever, then I think we can close this.

**Comment by rpappalax** [comment]
ff-tool 0.1.1 has been released
