### ISSUE TITLE
Replace OS detection with mozinfo

### ISSUE THREAD

**Issue by pdehaan** [rpappalax/ff-tool#67]
Saw **mozinfo** earlier and figured it's probably better to use that, instead of our [homegrown regex based OS detection](https://github.com/rpappalax/ff-tool/blob/593ffffd8a18fb3d3245aaedb2930e0fca767c7b/fftool/firefox_env_handler.py#L17-L28).

Will need a bit of Cygwin testing to make sure everything is still kosher (and it self-identifies as "windows").

Sample usage and output:

```py
import mozinfo

print("bits: {}".format(mozinfo.bits)) # 64
print("os: {}".format(mozinfo.os)) # mac
print("os_version: {}".format(mozinfo.os_version)) # 10.11
print("processor: {}".format(mozinfo.processor)) # x86_64
print("version: {}".format(mozinfo.version)) # OS X 10.11.4
```

**Comment by rpappalax** [comment]
:+1:
