### ISSUE TITLE
Add travis

### ISSUE THREAD

**Issue by rpappalax** [rpappalax/ff-tool#7]

**Comment by pdehaan** [comment]
Fixed via #19 (hopefully, will need another PR/push to confirm)

**Comment by pdehaan** [comment]
Clearly I missed something, since this isn't showing Travis on my latest cygwin PR.

**Comment by pdehaan** [comment]
@rpappalax Fixed this yesterday by enabling the repo. I'm :+1: with it currently, so we can close this.
