### ISSUE TITLE
fix: simplify args

### ISSUE THREAD

**Issue by rpappalax** [rpappalax/ff-tool#81]
The following args probably need a hollywood makeover

no-launch
no-profile
install-only

Per conversation, we'll drop no-profile altogether.

no-launch vs. install-only - aren't these really the same? (we prob only need one)
@pdehaan?

**Comment by pdehaan** [comment]
I forget the subtle difference between `--no-launch` and `--install-only` (which probably means there was/is no good reason to have both). 

https://github.com/rpappalax/ff-tool/blob/dev/fftool/main.py#L31-L48

It looks like we have the following flow:

1. "intelligently" download selected Firefox channel.
2. if user DID specify `--install-only` stop here. GOTO exit
3. if user did NOT specify `--no-profile` (double negative) then create a profile.
4. if user did NOT specify `--no-launch` (double negative) then launch newly downloaded Firefox.

So I think in most cases `--install-only` and `--no-launch` will have the same behavior. The only difference is if the user specifies `--no-profile`.

This is probably filled with some [not very] sharp edges. For example, I can seemingly specify `$ ff --no-launch` and it will (a) download the default Firefox channel, (b) create a new profile, (c) exit without launching a browser -- essentially creating an orphaned profile.
Not sure if we care, or it's worth trying to write a bunch of boilerplate code for "user specified -X and -Y but those may be somewhat mutually exclusive so we should throw warnings and exit with a non-zero exit code.

**Comment by rpappalax** [comment]
> I forget the subtle difference between --no-launch and --install-only (which probably means there was/is no good reason to have both). 
I had to think about it myself, but when I looked at the code, turns out one of them wasn't really being used at all.  there was, however, a conditional for the other to skip the launch step for the other one.

**Comment by rpappalax** [comment]
OK, when we do a `--no-launch`, we do mozdownload then install (which basically either extracts tarball [linux], unpacks dmg [OSX] or silently installs [Win], then conditionally aborts.
beyond that point, if we wanted a profile, we'd have to run mozprofile ...or... launch the browser.

**Comment by pdehaan** [comment]
Maybe we really only need `--install-only` for now and we can ✂️ away the rest of the :poop:.
Once that becomes limiting and we have legit use cases for the other flags, we can slowly add them back.

**Comment by rpappalax** [comment]
agreed

**Comment by pdehaan** [comment]
![](http://chatabout.com/assets/images/questions/2014/07/53c0790b40514.jpg)
