### ISSUE TITLE
Figure out how to automate install on Mac/Darwin

### ISSUE THREAD

**Issue by pdehaan** [rpappalax/ff-tool#9]
Need to find out how we can auto-mount a DMG and silent install.

I assume doing uninstall for Darwin is as simple as deleting the folder with the *.app.

**Comment by rpappalax** [comment]
Ok i remember now.
Mount to /Volumes with this command:
http://apple.stackexchange.com/a/73931
Then,
$ cp -R /Volumes/xxxx.app  <destination dir>
Then kick back with a book

**Comment by pdehaan** [comment]
### SMASHING, RICKY!

Oddly, this initial attempt seems to work (naturally we prefer to avoid `sudo` if possible, since that'd be blocking):

```sh
$ hdiutil attach firefox-45.0a1.en-US.mac.dmg -mountpoint foo45
expected   CRC32 $740D6CD9
/dev/disk3          	Apple_partition_scheme
/dev/disk3s1        	Apple_partition_map
/dev/disk3s2        	Apple_HFS                      	/Users/pdehaan/Downloads/foo45

$ ls -las foo45
total 1776
   4 lrwxrwxr-x@   1 pdehaan  staff      13 Nov 25 04:41   -> /Applications
   0 drwxr-xr-x@   7 pdehaan  staff     238 Nov 25 04:41 .
   0 drwx------+ 786 pdehaan  staff   26724 Feb 22 23:42 ..
  28 -rw-r--r--@   1 pdehaan  staff   12292 Nov 25 04:41 .DS_Store
1744 -rw-r--r--@   1 pdehaan  staff  891873 Nov 25 04:41 .VolumeIcon.icns
   0 drwxr-xr-x@   3 pdehaan  staff     102 Nov 25 04:41 .background
   0 drwxr-xr-x@   3 pdehaan  staff     102 Nov 25 04:18 FirefoxNightly.app

$ ./foo45/FirefoxNightly.app/Contents/MacOS/firefox --version
Mozilla Firefox 45.0a1
```

Although I think more investigation is needed, because if I unmount that device in Finder, it sort of disappears from my machine. So maybe your three-step process of attaching+copying+detaching is better.

**Comment by rpappalax** [comment]
Yay!!  Thanks man
Anxious to get back to this.

**Comment by pdehaan** [comment]
Closing. I'm happy-_ish_ with our solution in 16aff3ba38f31f93e180241981d3cf9705a6fceb.
I'll do a future PR to move the hdiutil stuff into a separate module to mask some of the horror.
