### ISSUE TITLE
Rename _temp to .cache

### ISSUE THREAD

**Issue by pdehaan** [rpappalax/ff-tool#96]
@rpappalax suggested renaming the `_temp` directory to `.temp` [so it is hidden].
Probably pretty trivial, and just a simple search-replace in about 10 places (docs, .ini, .py).

**Comment by pdehaan** [comment]
Ref: #25

**Comment by rpappalax** [comment]
Per conversation w/ @pdehaan, we'll go with .cache instead of .temp
